blank_issues_enabled: true
contact_links:
  - name: Ask a question on how to use winter-challenge-2024
    about: For general-purpose questions and answers, see the Discussions section.
    url: https://github.com/MathieuSoysal/Winter_Challenge_2024/discussions
